### ISSUE TITLE
change colours

### ISSUE THREAD

**Issue by ayuushhh** [ayuushhh/Frontend-Mentor-Social-proof-section#1]
change color of the names of buyers

**Comment by aishwaryeay** [comment]
can you assign this to me?

**Comment by rajmunkhan** [comment]
@ayuushhh I would like to work on this, please assign it to me.

**Comment by wimanshaherath** [comment]
@ayuushhh can I work on this?

**Comment by ayuushhh** [comment]
make a pr directly ill merge
